name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Code ko check karega
      - uses: actions/checkout@v3

      # Yeh 'Ready-Made Robot' hai jo App banata hai
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      # App ko upload karega taaki aap download kar sako
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Jarvis-APK
          path: bin/*.apk
